# General settings
general:
  seed: 42

# MediaPipe configuration
mediapipe:
  min_detection_confidence: 0.3
  max_num_hands: 1
  model_path: "../models/hand_landmarker.task"

# Random Forest hyperparameters
random_forest:
  n_estimators: 200
  max_depth: None
  min_samples_split: 10
  min_samples_leaf: 1
  max_features: "sqrt"
  class_weight: "balanced"

# XGBoost hyperparameters
xgboost:
  n_estimators: 200
  max_depth: 8
  learning_rate: 0.05
  min_child_weight: 3
  subsample: 0.7
  colsample_bytree: 0.9
  objective: "multi:softprob" # Para clasificación multiclase

# Neural Network hyperparameters
neural_network:
  hidden_dim_1: 256
  hidden_dim_2: 128
  epochs: 500
  batch_size: 256
  learning_rate: 0.001
